stages:
  - build
  - sonar
  - publish

variables:
  PROJECT_PREFIX: "pn"
  CI_PROJECT_NAMESPACE: "company-pn"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle
      
publish:
  stage: publish
  image: registry.company.com/gitops/templates:gradle-8-jdk-21
  script:
    - gradle publish
  cache:
    key: gradle-cache-key
    paths:
      - .gradle/caches
    policy: pull
  tags:
    - noncluster-runner
  only:
    refs:
      - tags
  artifacts:
    paths:
      - build/libs/*.jar

include:
  - project: 'gitops/templates'
    ref: master
    file:
      - '/gitlab-ci/.build.yml'
      - '/gitlab-ci/.sonar.yml'
